// <auto-generated />
using System;
using EntiryFrameworkCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntiryFrameworkCore.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview3.19554.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntiryFrameworkCore.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Modify")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Date_Created = new DateTime(2021, 5, 6, 11, 39, 5, 992, DateTimeKind.Local).AddTicks(6523),
                            Date_Modify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "A Super User is a person from the department who has a profound understanding of internal processes and is responsible for knowledge management inside of the department",
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            Date_Created = new DateTime(2021, 5, 6, 11, 39, 5, 996, DateTimeKind.Local).AddTicks(2161),
                            Date_Modify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "A simple user is the user who is a daily user based on the settings and authorizations provided by the Super User and has limited access due to that.",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("EntiryFrameworkCore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Modify")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Date_Created = new DateTime(2021, 5, 6, 11, 39, 5, 996, DateTimeKind.Local).AddTicks(9344),
                            Date_Modify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kensonza@gmail.com",
                            First_Name = "Kenneth Isaac",
                            Last_Name = "Sonza",
                            Password = "1234567890",
                            RoleId = 1,
                            Status = 1,
                            Username = "k.sonza"
                        },
                        new
                        {
                            UserId = 2,
                            Date_Created = new DateTime(2021, 5, 6, 11, 39, 5, 997, DateTimeKind.Local).AddTicks(296),
                            Date_Modify = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "crazykalang@yahoo.com",
                            First_Name = "Maria Carla",
                            Last_Name = "Franco",
                            Password = "1234567890",
                            RoleId = 2,
                            Status = 1,
                            Username = "c.kalang"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
